"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['USER_PSQL'],
        'PASSWORD': os.environ['USER_PSQL_PASSWORD'],
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

users = [
#    [
        {
            'username': "user1",
            "password": "test1234567890",
            "email": "user1@test.com",
            "first_name": "John",
            "last_name": "Smith",
            "role": "admin",
            "phone": "1234567890",
            "address": "123 Main St",
            "city": "New York",
            "state": "NY",
            "zipcode": "10001",
        },
        {
            'username': "user2",
            "password": "test1234567890",
            "email": "user2@test.com",
            "first_name": "Emma",
            "last_name": "Johnson",
            "role": "admin",
            "phone": "2345678901",
            "address": "456 Oak Ave",
            "city": "Los Angeles",
            "state": "CA",
            "zipcode": "90001",
        },
        {
            'username': "user3",
            "password": "test1234567890",
            "email": "user3@test.com",
            "first_name": "Michael",
            "last_name": "Brown",
            "role": "admin",
            "phone": "3456789012",
            "address": "789 Pine St",
            "city": "Chicago",
            "state": "IL",
            "zipcode": "60601",
        },
        {
            'username': "user4",
            "password": "test1234567890",
            "email": "user4@test.com",
            "first_name": "Sarah",
            "last_name": "Davis",
            "role": "admin",
            "phone": "4567890123",
            "address": "321 Elm St",
            "city": "Houston",
            "state": "TX",
            "zipcode": "77001",
        },
        {
            'username': "user5",
            "password": "test1234567890",
            "email": "user5@test.com",
            "first_name": "David",
            "last_name": "Wilson",
            "role": "admin",
            "phone": "5678901234",
            "address": "654 Maple Dr",
            "city": "Phoenix",
            "state": "AZ",
            "zipcode": "85001",
        },
        {
            'username': "user6",
            "password": "test1234567890",
            "email": "user6@test.com",
            "first_name": "Lisa",
            "last_name": "Anderson",
            "role": "admin",
            "phone": "6789012345",
            "address": "987 Cedar Ln",
            "city": "Philadelphia",
            "state": "PA",
            "zipcode": "19101",
        },
        {
            'username': "user7",
            "password": "test1234567890",
            "email": "user7@test.com",
            "first_name": "James",
            "last_name": "Taylor",
            "role": "admin",
            "phone": "7890123456",
            "address": "741 Birch Rd",
            "city": "San Antonio",
            "state": "TX",
            "zipcode": "78201",
        },
        {
            'username': "user8",
            "password": "test1234567890",
            "email": "user8@test.com",
            "first_name": "Jennifer",
            "last_name": "Martinez",
            "role": "admin",
            "phone": "8901234567",
            "address": "852 Willow Way",
            "city": "San Diego",
            "state": "CA",
            "zipcode": "92101",
        },
        {
            'username': "user9",
            "password": "test1234567890",
            "email": "user9@test.com",
            "first_name": "Robert",
            "last_name": "Garcia",
            "role": "admin",
            "phone": "9012345678",
            "address": "963 Spruce Ave",
            "city": "Dallas",
            "state": "TX",
            "zipcode": "75201",
        },
        {
            'username': "user10",
            "password": "test1234567890",
            "email": "user10@test.com",
            "first_name": "Maria",
            "last_name": "Rodriguez",
            "role": "admin",
            "phone": "0123456789",
            "address": "159 Ash Blvd",
            "city": "San Jose",
            "state": "CA",
            "zipcode": "95101",
        }
    #]
]

for user in users:
    new_user = user
    CustomUser.objects.create_user(**new_user)
